import{a as w,i as d}from"./assets/vendor-22aaac4a.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function c(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=c(t);fetch(t.href,r)}})();function b(e){return`<li class="gallery-item">
  <a class="gallery-link" href="${e.largeImageURL}">
    <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}" />
  </a>
   <div class="image-details">
                    <p>Likes: ${e.likes}</p>
                    <p>Views: ${e.views}</p>
                    <p>Comments: ${e.comments}</p>
                    <p>Downloads: ${e.downloads}</p>
                </div>
</li>`}function v(e){return e.map(b).join("")}async function u(e,o){const c="https://pixabay.com",i="/api/",r={key:"42305658-75508782eac06a666c1fb928b",image_type:"photo",orientation:"horizontal",safesearch:"true",q:e,per_page:15,page:o},s=`${c}${i}?${new URLSearchParams(r)}`;return(await w.get(s)).data}const P=document.querySelector(".js-search-form"),m=document.querySelector(".gallery"),f=document.querySelector(".js-loader"),l=document.querySelector(".js-btn-load");let n,a,p;P.addEventListener("submit",S);l.addEventListener("click",$);async function S(e){e.preventDefault(),n=e.target.elements.search.value.trim(),a=1,y(),n||I("Sorry, there are no images matching your search query. Please try again!");const o=await u(n,a);console.log(o),p=Math.ceil(o.totalHits/15),m.innerHTML="",g(o.hits),h(),L(),e.target.reset()}async function $(){if(a+=1,!n)return d.warning({title:"Warning",message:"Please enter a search query",position:"topCenter"});y();const e=await u(n,a);g(e.hits),h(),L()}function g(e){const o=v(e);m.insertAdjacentHTML("beforeend",o)}function q(){l.classList.remove("hidden")}function E(){l.classList.add("hidden")}function y(){f.classList.remove("hidden")}function h(){f.classList.add("hidden")}function L(){a>=p?E():q()}function I(e){d.error({title:"Error",message:e,position:"topCenter"})}
//# sourceMappingURL=commonHelpers.js.map
